Repository MyChore/MyChore-IOS, pull requests merged in 2023-08, with the labels that each got.

#3 Feat/1 login UI
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyChore/MyChore/AppDelegate.swift
  MyChore/MyChore/Assets.xcassets/agree_check.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/agree_check.imageset/agree_check.svg
  MyChore/MyChore/Assets.xcassets/image_add.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/image_add.imageset/image_add.svg
  MyChore/MyChore/Assets.xcassets/login_apple.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/login_apple.imageset/login_apple.svg
  MyChore/MyChore/Assets.xcassets/login_kakao.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/login_kakao.imageset/login_kakao.svg
  MyChore/MyChore/Assets.xcassets/login_logotype.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/login_logotype.imageset/login_logotype.svg
  MyChore/MyChore/Assets.xcassets/login_message.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/login_message.imageset/login_message.png
  MyChore/MyChore/Info.plist
  MyChore/MyChore/SceneDelegate.swift
  MyChore/MyChore/Utility/Extension/String+.swift
  MyChore/View/Login/AgreementViewController.swift
  MyChore/View/Login/LoginViewController.swift
  MyChore/View/Login/NicknameViewController.swift
  MyChore/View/Login/TeamCodeViewController.swift
  MyChore/View/Login/UserInfoViewController.swift
Labels: ✨ Feature

#9 [Feat] 마이페이지 ui 구현
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Assets.xcassets/Mypage/Contents.json
  MyChore/MyChore/Assets.xcassets/Mypage/info.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/Mypage/info.imageset/image 9.png
  MyChore/MyChore/Assets.xcassets/Mypage/next.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/Mypage/next.imageset/next.svg
  MyChore/MyChore/Assets.xcassets/Mypage/notice.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/Mypage/notice.imageset/image 7.png
  MyChore/MyChore/Assets.xcassets/Mypage/notification.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/Mypage/notification.imageset/ala.png
  MyChore/MyChore/Assets.xcassets/Mypage/qa.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/Mypage/qa.imageset/image 8.png
  MyChore/MyChore/Assets.xcassets/navigation/Contents.json
  MyChore/MyChore/Assets.xcassets/navigation/back.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/navigation/back.imageset/Group 596.svg
  MyChore/MyChore/Info.plist
  MyChore/MyChore/SceneDelegate.swift
  MyChore/MyChore/Utility/Extension/CGFloat+.swift
  MyChore/MyChore/Utility/Extension/UIButton+.swift
  MyChore/View/Mypage/Cell/InfoCell.swift
  MyChore/View/Mypage/Cell/MyPageCell.swift
  MyChore/View/Mypage/InfoViewController.swift
  MyChore/View/Mypage/MypageMainViewController.swift
  MyChore/View/Mypage/NotificationSettingViewController.swift
  MyChore/View/Mypage/UserInfoChangeViewController.swift
Labels: ✨ Feature, 유상

#11 [Feat] 캘린더뷰 ui 구현
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Presentation/View/Calendar/CalendarViewController.swift
  MyChore/MyChore/Presentation/View/Calendar/CheckBoxButton.swift
  MyChore/MyChore/Utility/Extension/UIImage+.swift
Labels: ✨ Feature, 혜민

#16 [Feat] 마이페이지 api 연결
  MyChore/Model/Login/FirebaseStorageManager.swift
  MyChore/Model/Mypage/MypageModel.swift
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  MyChore/MyChore/SceneDelegate.swift
  MyChore/Service/Login/APIManager.swift
  MyChore/Service/Login/LoginService.swift
  MyChore/Service/Mypage/MypageService.swift
  MyChore/View/Login/NicknameViewController.swift
  MyChore/View/Mypage/MypageMainViewController.swift
  MyChore/View/Mypage/UserInfoChangeViewController.swift
  MyChore/ViewModel/Login/LoginViewModel.swift
  MyChore/ViewModel/Mypage/MypageViewModel.swift
Labels: ✨ Feature, 유상

#17 #12 chore: 폴더 변경
  MyChore/MyChore.xcodeproj/project.pbxproj
Labels: 📄 Document

#18 [Feat] HomeView UI 구현
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Presentation/View/Components/CheckBoxButton.swift
  MyChore/MyChore/Presentation/View/Components/Tag.swift
  MyChore/MyChore/Presentation/View/Home/Cell/TodoTableCell.swift
  MyChore/MyChore/Presentation/View/Home/HomeViewController.swift
  MyChore/MyChore/Utility/Extension/Date+.swift
Labels: ✨ Feature, 혜민

#19 [Feat] Custom TabBar 구현
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Assets.xcassets/TabBar/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/add.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/add.imageset/Group 616.png
  MyChore/MyChore/Assets.xcassets/TabBar/add.imageset/Group 616@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/add.imageset/Group 616@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/calendar.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/calendar.imageset/Group 617.png
  MyChore/MyChore/Assets.xcassets/TabBar/calendar.imageset/Group 617@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/calendar.imageset/Group 617@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/home.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/home.imageset/Group 614.png
  MyChore/MyChore/Assets.xcassets/TabBar/home.imageset/Group 614@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/home.imageset/Group 614@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/manage.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/manage.imageset/Group 620.png
  MyChore/MyChore/Assets.xcassets/TabBar/manage.imageset/Group 620@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/manage.imageset/Group 620@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/profile.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/profile.imageset/Group 610.png
  MyChore/MyChore/Assets.xcassets/TabBar/profile.imageset/Group 610@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/profile.imageset/Group 610@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_calendar.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/selected_calendar.imageset/Group 609.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_calendar.imageset/Group 609@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_calendar.imageset/Group 609@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_home.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/selected_home.imageset/Group 614.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_home.imageset/Group 614@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_home.imageset/Group 614@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_manage.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/selected_manage.imageset/Group 620.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_manage.imageset/Group 620@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_manage.imageset/Group 620@3x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_profile.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/TabBar/selected_profile.imageset/Group 618.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_profile.imageset/Group 618@2x.png
  MyChore/MyChore/Assets.xcassets/TabBar/selected_profile.imageset/Group 618@3x.png
  MyChore/MyChore/Presentation/View/Calendar/CalendarViewController.swift
  MyChore/MyChore/Presentation/View/Home/HomeViewController.swift
  MyChore/MyChore/Presentation/View/MCTabBarViewController.swift
Labels: ✨ Feature, 혜민

#20 [Fix] CalendarView 이미지 변경
  MyChore/MyChore/Assets.xcassets/down_chevron.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/down_chevron.imageset/Group 677.png
  MyChore/MyChore/Assets.xcassets/down_chevron.imageset/Group 677@2x.png
  MyChore/MyChore/Assets.xcassets/down_chevron.imageset/Group 677@3x.png
  MyChore/MyChore/Assets.xcassets/group.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/group.imageset/Group 640.png
  MyChore/MyChore/Assets.xcassets/group.imageset/Group 640@2x.png
  MyChore/MyChore/Assets.xcassets/group.imageset/Group 640@3x.png
  MyChore/MyChore/Assets.xcassets/right_chevron.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/right_chevron.imageset/Group 649.png
  MyChore/MyChore/Assets.xcassets/right_chevron.imageset/Group 649@2x.png
  MyChore/MyChore/Assets.xcassets/right_chevron.imageset/Group 649@3x.png
  MyChore/MyChore/Assets.xcassets/up_and_down.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/up_and_down.imageset/Group 643.png
  MyChore/MyChore/Assets.xcassets/up_and_down.imageset/Group 643@2x.png
  MyChore/MyChore/Assets.xcassets/up_and_down.imageset/Group 643@3x.png
  MyChore/MyChore/Presentation/View/Calendar/CalendarViewController.swift
Labels: ✏️ Style, 혜민

#22 [Fix] 로그인 UI 수정
  MyChore/View/Login/LoginViewController.swift
Labels: ✏️ Style

#26 [Chore] 파일 구조 변경
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Presentation/View/ChoreAdd/ChoreAddMainViewController.swift
  MyChore/MyChore/Presentation/View/ChoreAdd/FurnitureSelectViewController.swift
  MyChore/MyChore/Presentation/View/ChoreAdd/ManagerSelectViewController.swift
  MyChore/MyChore/Presentation/View/ChoreAdd/RepeatEndViewController.swift
  MyChore/MyChore/Presentation/View/ChoreAdd/RepeatPeriodViewController.swift
  MyChore/MyChore/Presentation/View/ChoreAdd/RepeatSelectViewController.swift
  MyChore/MyChore/Presentation/View/Login/AgreementViewController.swift
  MyChore/MyChore/Presentation/View/Login/LoginViewController.swift
  MyChore/MyChore/Presentation/View/Login/NicknameViewController.swift
  MyChore/MyChore/Presentation/View/Login/TeamCodeViewController.swift
  MyChore/MyChore/Presentation/View/Login/UserInfoViewController.swift
  MyChore/MyChore/Presentation/View/Mypage/Cell/InfoCell.swift
  MyChore/MyChore/Presentation/View/Mypage/Cell/MyPageCell.swift
  MyChore/MyChore/Presentation/View/Mypage/InfoViewController.swift
  MyChore/MyChore/Presentation/View/Mypage/MypageMainViewController.swift
  MyChore/MyChore/Presentation/View/Mypage/NotificationSettingViewController.swift
  MyChore/MyChore/Presentation/View/Mypage/UserInfoChangeViewController.swift
  MyChore/MyChore/Presentation/ViewModel/Login/LoginViewModel.swift
  MyChore/MyChore/Presentation/ViewModel/Mypage/MypageViewModel.swift
  MyChore/MyChore/SceneDelegate.swift
Labels: ⚙️ Build Up, 혜민

#27 [Chore] setting folder
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Presentation/View/MCTabBarViewController.swift
  MyChore/MyChore/Presentation/View/Manage/ManageMainViewController.swift
Labels: ⚙️ Build Up

#31 [Feat] ManageMasterView UI 구현
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Assets.xcassets/gear.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/gear.imageset/Group 647.png
  MyChore/MyChore/Assets.xcassets/gear.imageset/Group 647@2x.png
  MyChore/MyChore/Assets.xcassets/gear.imageset/Group 647@3x.png
  MyChore/MyChore/Assets.xcassets/menu_bar.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/menu_bar.imageset/Group 412.png
  MyChore/MyChore/Assets.xcassets/menu_bar.imageset/Group 412@2x.png
  MyChore/MyChore/Assets.xcassets/menu_bar.imageset/Group 412@3x.png
  MyChore/MyChore/Presentation/View/MCTabBarViewController.swift
  MyChore/MyChore/Presentation/View/Manage/Master/GroupMemberSettingViewController.swift
  MyChore/MyChore/Presentation/View/Manage/Master/ManageMasterViewController.swift
Labels: ✨ Feature, 혜민

#32 [Feat] ManageMasterView UI
  MyChore/MyChore/Presentation/View/Manage/Master/GroupMemberSettingViewController.swift
  MyChore/MyChore/Presentation/View/Manage/Master/ManageMasterViewController.swift
Labels: ✨ Feature, 혜민

#34 [Add] 앱 로고 추가
  MyChore/MyChore/Assets.xcassets/AppIcon.appiconset/Contents.json
  MyChore/MyChore/Assets.xcassets/AppIcon.appiconset/로고final3 (1).png
Labels: 혜민

#37 [Feat] 평면도 만들기 UI 구현
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Assets.xcassets/AddFloor/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/copy_button.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/copy_button.imageset/copy_button.svg
  MyChore/MyChore/Assets.xcassets/AddFloor/floorAddImage.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/floorAddImage.imageset/floorAddImage.png
  MyChore/MyChore/Assets.xcassets/AddFloor/oneroom.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/oneroom.imageset/oneroom.png
  MyChore/MyChore/Assets.xcassets/AddFloor/oneroom_selected.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/oneroom_selected.imageset/oneroom_selected.png
  MyChore/MyChore/Assets.xcassets/AddFloor/separationroom.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/separationroom.imageset/separationroom.png
  MyChore/MyChore/Assets.xcassets/AddFloor/separationroom_selected.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/separationroom_selected.imageset/separationroom_selected.png
  MyChore/MyChore/Assets.xcassets/AddFloor/threeroom.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/threeroom.imageset/threeroom.png
  MyChore/MyChore/Assets.xcassets/AddFloor/threeroom_selected.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/threeroom_selected.imageset/threeroom_selected.png
  MyChore/MyChore/Assets.xcassets/AddFloor/tworoom.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/tworoom.imageset/tworoom.png
  MyChore/MyChore/Assets.xcassets/AddFloor/tworoom_selected.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/AddFloor/tworoom_selected.imageset/tworoom_selected.png
  MyChore/MyChore/Presentation/View/AddFloor/AddFloorCompleteViewController.swift
  MyChore/MyChore/Presentation/View/AddFloor/AddFloorFirstViewController.swift
  MyChore/MyChore/Presentation/View/AddFloor/AddFloorSecondViewController.swift
  MyChore/MyChore/Presentation/View/AddFloor/AddFloorThirdViewController.swift
  MyChore/MyChore/Presentation/View/AddFloor/Cell/RoomSelectCell.swift
  MyChore/MyChore/SceneDelegate.swift
Labels: ✨ Feature, 유상

#40 [Feat] 평면도 생성 api 연결
  MyChore/Model/Floor/FloorModel.swift
  MyChore/MyChore.xcodeproj/project.pbxproj
  MyChore/MyChore/Presentation/Floor/FloorViewModel.swift
  MyChore/MyChore/Presentation/View/AddFloor/AddFloorCompleteViewController.swift
  MyChore/MyChore/Presentation/View/AddFloor/AddFloorSecondViewController.swift
  MyChore/MyChore/Presentation/View/AddFloor/AddFloorThirdViewController.swift
  MyChore/MyChore/SceneDelegate.swift
  MyChore/Service/Floor/FloorService.swift
Labels: ✨ Feature, 유상

#42 [Test] 데모데이용 이미지 에셋 추가
  MyChore/MyChore/Assets.xcassets/floor_one_demension.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/floor_one_demension.imageset/메인_2룸_방2.png
  MyChore/MyChore/Assets.xcassets/floor_one_demension.imageset/메인_2룸_방2@2x.png
  MyChore/MyChore/Assets.xcassets/floor_one_demension.imageset/메인_2룸_방2@3x.png
  MyChore/MyChore/Assets.xcassets/illustration.imageset/Contents.json
  MyChore/MyChore/Assets.xcassets/illustration.imageset/그림자 넣는중-01 3.png
  MyChore/MyChore/Assets.xcassets/illustration.imageset/그림자 넣는중-01 3@2x.png
  MyChore/MyChore/Assets.xcassets/illustration.imageset/그림자 넣는중-01 3@3x.png
  MyChore/MyChore/Presentation/View/Calendar/CalendarViewController.swift
  MyChore/MyChore/Presentation/View/Home/Cell/TodoTableCell.swift
  MyChore/MyChore/Presentation/View/Home/HomeViewController.swift
  MyChore/MyChore/Presentation/View/Manage/Master/ManageMasterViewController.swift
Labels: 혜민, 🧪 Test
